version: "3.7"
services:
  spring-app:
    container_name: bookstore-app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgre-db
    environment:
      POSTGRES_DB: bookstore-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin-data:








#version: "3.7"
#services:
#  api_service:
#    build: .
#    restart: always
#    ports:
#      - 8080:8080
#    networks:
#      - springapimysql-net
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3307/bookstoredb?allowPublicKeyRetrieval=true
#    depends_on:
#      - mysqldb
#
#    volumes:
#      - .m2:/root/.m2
#
#  mysqldb:
#    image: "mysql:8.0.2"
#    restart: always
#    ports:
#      - 3307:3306
#    networks:
#      - springapimysql-net
#    environment:
#      MYSQL_DATABASE: bookstoredb
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#networks:
#  springapimysql-net:
#



  #version: '3.7'
#services:
#  mysql:
#    image: mysql:8.2
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: bookstoredb
#
#  bookstore-app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      DB_CONNECTION_IP: mysql
#      DB_CONNECTION_PORT: 3306
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookstoredb?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_MAIL_HOST: smtp.gmail.com
#      SPRING_MAIL_PORT: 587
#      SPRING_MAIL_USERNAME: ibrahimqarayev77@gmail.com
#      SPRING_MAIL_PASSWORD: xxrw sxdq zjog evpg
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
#      SPRING_SECURITY_JWT_SECRET_KEY: 3ev4PTCo6RctpT0kCgcn4DV/rdCcJYw9yKKfdCEVPLr7/gQq57bUxjlw83WU1L1iWCvGV/w9mZfveeJEAfz7vg==
#      SPRING_SECURITY_JWT_EXPIRATION: 86400000








  #version: '3.7'
#services:
#  mysql:
#    image: mysql:8.0.2
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_USER: root
#      MYSQL_DATABASE: bookstoredb
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#
#  bookstore-app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: &connectionUrl jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3306}/bookstoredb?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
#      SPRING_DATASOURCE_USERNAME: ibrahim
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_MAIL_HOST: smtp.gmail.com
#      SPRING_MAIL_PORT: 587
#      SPRING_MAIL_USERNAME: ibrahimqarayev77@gmail.com
#      SPRING_MAIL_PASSWORD: xxrw sxdq zjog evpg
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
#      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
#      SPRING_SECURITY_JWT_SECRET_KEY: 3ev4PTCo6RctpT0kCgcn4DV/rdCcJYw9yKKfdCEVPLr7/gQq57bUxjlw83WU1L1iWCvGV/w9mZfveeJEAfz7vg==
#      SPRING_SECURITY_JWT_EXPIRATION: 86400000
#

  # Diğer servisler buraya eklenebilir.








#version: "3.7"
#services:
#  api_service:
#    build: .
#    restart: always
#    ports:
#      - 8080:8080
#    networks:
#      - springapimysql-net
#    environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3306/liquitest?allowPublicKeyRetrieval=true
#    depends_on:
#      - mysqldb
#
#    volumes:
#      - .m2:/root/.m2
#
#  mysqldb:
#    image: "mysql:8.0"
#    restart: always
#    ports:
#      - 3307:3306
#    networks:
#      - springapimysql-net
#    environment:
#      MYSQL_DATABASE: liquitest
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#networks:
#  springapimysql-net:
#
#
#volumes:
#  db:
#
#





#version: '3.1'
#services:
#  mysqldb:
#    image: "mysql:8.0"
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_DATABASE: liquitest
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: "!i@b#o"


#version: '3.8'
#
#services:
#  db:
#    container_name: bookstore-db
#    image: mysql:latest
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: bookstore
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql  # Docker veri sürümü
#
#volumes:
#  mysql_data:  # Docker veri sürümünün adı