spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: root
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailformyapplication@gmail.com
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: 3ev4PTCo6RctpT0kCgcn4DV/rdCcJYw9yKKfdCEVPLr7/gQq57bUxjlw83WU1L1iWCvGV/w9mZfveeJEAfz7vg==
      expiration: 86400000



